server:
  port: 8080

app:
  name: 抢单辅助程序
  version: 1.0.0
  
  encryption:
    fixed-string: LAB2025
    algorithms:
      - BASE64
      - MD5
      - SHA256
  
  api:
    base-url: http://localhost:8080/api
    login-url: /login
    token-validate-url: /token/validate
    orders-query-url: /orders/query
    orders-grab-url: /orders/grab
    
  scheduler:
    token-refresh-interval: 600000
    
  logging:
    base-path: logs

spring:
  application:
    name: order-grabber
  main:
    web-application-type: servlet

logging:
  level:
    com.scmp.ordergrabber: DEBUG
    root: INFO